branch-defaults:
  master:
    environment: HelloWorld2-dev
global:
  application_name: HelloWorld2
  default_ec2_keyname: pbp
  default_platform: Node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
